// ============================================================
// MODEL: CV
// Represents an AI-generated tailored CV for a specific job.
// Contains structured sections generated by CVGenerationService.
// ============================================================

class CV {
  final String id;
  final String jobId;
  final String jobTitle;
  final String company;
  CVContent content;
  final DateTime generatedAt;
  List<CVFeedback> feedbackHistory;
  int regenerationCount;
  String? localPdfPath;

  CV({
    required this.id,
    required this.jobId,
    required this.jobTitle,
    required this.company,
    required this.content,
    DateTime? generatedAt,
    List<CVFeedback>? feedbackHistory,
    this.regenerationCount = 0,
    this.localPdfPath,
  })  : generatedAt = generatedAt ?? DateTime.now(),
        feedbackHistory = feedbackHistory ?? [];

  /// Returns true if the CV has been modified based on user feedback.
  bool get wasModified => regenerationCount > 0;

  /// Adds feedback and increments regeneration counter.
  void applyFeedback(CVFeedback feedback) {
    feedbackHistory.add(feedback);
    regenerationCount++;
  }

  @override
  String toString() =>
      'CV(jobTitle: $jobTitle, regenerations: $regenerationCount)';

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'jobId': jobId,
      'jobTitle': jobTitle,
      'company': company,
      'content': content.toJson(),
      'generatedAt': generatedAt.toIso8601String(),
      'feedbackHistory': feedbackHistory.map((e) => e.toJson()).toList(),
      'regenerationCount': regenerationCount,
      'localPdfPath': localPdfPath,
    };
  }

  factory CV.fromJson(Map<String, dynamic> json) {
    return CV(
      id: json['id'] ?? '',
      jobId: json['jobId'] ?? '',
      jobTitle: json['jobTitle'] ?? '',
      company: json['company'] ?? '',
      content: CVContent.fromJson(json['content'] ?? {}),
      generatedAt: json['generatedAt'] != null 
          ? DateTime.parse(json['generatedAt']) 
          : DateTime.now(),
      feedbackHistory: (json['feedbackHistory'] as List? ?? [])
          .map((e) => CVFeedback.fromJson(e))
          .toList(),
      regenerationCount: json['regenerationCount'] ?? 0,
      localPdfPath: json['localPdfPath'],
    );
  }
}

// ============================================================
// MODEL: CVContent
// Structured sections of the generated CV.
// ============================================================

class CVContent {
  String summary;
  List<String> highlightedSkills;
  List<CVExperience> relevantExperiences;
  List<String> educationEntries;
  List<String> certifications;
  List<String> keyAchievements;
  String targetRole;

  CVContent({
    required this.summary,
    required this.highlightedSkills,
    required this.relevantExperiences,
    required this.educationEntries,
    this.certifications = const [],
    this.keyAchievements = const [],
    this.targetRole = '',
  });

  Map<String, dynamic> toJson() {
    return {
      'summary': summary,
      'skills': highlightedSkills,
      'experiences': relevantExperiences.map((e) => e.toJson()).toList(),
      'educationEntries': educationEntries,
      'certifications': certifications,
      'keyAchievements': keyAchievements,
      'targetRole': targetRole,
    };
  }

  factory CVContent.fromJson(Map<String, dynamic> json) {
    return CVContent(
      summary: json['summary'] ?? '',
      highlightedSkills: List<String>.from(json['skills'] ?? []),
      relevantExperiences: (json['experiences'] as List? ?? [])
          .map((e) => CVExperience.fromJson(e))
          .toList(),
      educationEntries: List<String>.from(json['educationEntries'] ?? []),
      certifications: List<String>.from(json['certifications'] ?? []),
      keyAchievements: List<String>.from(json['keyAchievements'] ?? []),
      targetRole: json['targetRole'] ?? '',
    );
  }
}

// ============================================================
// MODEL: CVExperience
// A tailored experience entry inside a generated CV.
// Only the most relevant responsibilities from the user's full
// experience history are extracted and included.
// ============================================================

class CVExperience {
  final String jobTitle;
  final String company;
  final String duration;
  final List<String> tailoredBullets;

  CVExperience({
    required this.jobTitle,
    required this.company,
    required this.duration,
    required this.tailoredBullets,
  });

  Map<String, dynamic> toJson() {
    return {
      'jobTitle': jobTitle,
      'company': company,
      'duration': duration,
      'achievements': tailoredBullets,
    };
  }

  factory CVExperience.fromJson(Map<String, dynamic> json) {
    return CVExperience(
      jobTitle: json['jobTitle'] ?? '',
      company: json['company'] ?? '',
      duration: json['duration'] ?? '',
      tailoredBullets: List<String>.from(json['achievements'] ?? []),
    );
  }
}

// ============================================================
// MODEL: CVFeedback
// Records user feedback on a generated CV and modification request.
// ============================================================

class CVFeedback {
  final String id;
  final String feedbackText;
  final DateTime timestamp;

  CVFeedback({
    required this.id,
    required this.feedbackText,
    DateTime? timestamp,
  }) : timestamp = timestamp ?? DateTime.now();

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'feedbackText': feedbackText,
      'timestamp': timestamp.toIso8601String(),
    };
  }

  factory CVFeedback.fromJson(Map<String, dynamic> json) {
    return CVFeedback(
      id: json['id'] ?? '',
      feedbackText: json['feedbackText'] ?? '',
      timestamp: json['timestamp'] != null 
          ? DateTime.parse(json['timestamp']) 
          : DateTime.now(),
    );
  }
}

