// ============================================================
// MODEL: CV
// Represents an AI-generated tailored CV for a specific job.
// Contains structured sections generated by CVGenerationService.
// ============================================================

class CV {
  final String id;
  final String jobId;
  final String jobTitle;
  final String company;
  CVContent content;
  final DateTime generatedAt;
  List<CVFeedback> feedbackHistory;
  int regenerationCount;

  CV({
    required this.id,
    required this.jobId,
    required this.jobTitle,
    required this.company,
    required this.content,
    DateTime? generatedAt,
    List<CVFeedback>? feedbackHistory,
    this.regenerationCount = 0,
  })  : generatedAt = generatedAt ?? DateTime.now(),
        feedbackHistory = feedbackHistory ?? [];

  /// Returns true if the CV has been modified based on user feedback.
  bool get wasModified => regenerationCount > 0;

  /// Adds feedback and increments regeneration counter.
  void applyFeedback(CVFeedback feedback) {
    feedbackHistory.add(feedback);
    regenerationCount++;
  }

  @override
  String toString() =>
      'CV(jobTitle: $jobTitle, regenerations: $regenerationCount)';
}

// ============================================================
// MODEL: CVContent
// Structured sections of the generated CV.
// ============================================================

class CVContent {
  String summary;
  List<String> highlightedSkills;
  List<CVExperience> relevantExperiences;
  List<String> educationEntries;
  List<String> certifications;
  List<String> keyAchievements;
  String targetRole;

  CVContent({
    required this.summary,
    required this.highlightedSkills,
    required this.relevantExperiences,
    required this.educationEntries,
    this.certifications = const [],
    this.keyAchievements = const [],
    this.targetRole = '',
  });

  factory CVContent.fromJson(Map<String, dynamic> json) {
    return CVContent(
      summary: json['summary'] ?? '',
      highlightedSkills: List<String>.from(json['skills'] ?? []),
      relevantExperiences: (json['experiences'] as List? ?? [])
          .map((e) => CVExperience.fromJson(e))
          .toList(),
      educationEntries: [], // These aren't AI generated, so leave empty. Handled in UI if needed.
    );
  }
}

// ============================================================
// MODEL: CVExperience
// A tailored experience entry inside a generated CV.
// Only the most relevant responsibilities from the user's full
// experience history are extracted and included.
// ============================================================

class CVExperience {
  final String jobTitle;
  final String company;
  final String duration;
  final List<String> tailoredBullets;

  CVExperience({
    required this.jobTitle,
    required this.company,
    required this.duration,
    required this.tailoredBullets,
  });

  factory CVExperience.fromJson(Map<String, dynamic> json) {
    return CVExperience(
      jobTitle: json['jobTitle'] ?? '',
      company: json['company'] ?? '',
      duration: '${json['startDate'] ?? ''} - ${json['endDate'] ?? ''}',
      tailoredBullets: List<String>.from(json['achievements'] ?? []),
    );
  }
}

// ============================================================
// MODEL: CVFeedback
// Records user feedback on a generated CV and modification request.
// ============================================================

class CVFeedback {
  final String id;
  final String feedbackText;
  final DateTime timestamp;

  CVFeedback({
    required this.id,
    required this.feedbackText,
    DateTime? timestamp,
  }) : timestamp = timestamp ?? DateTime.now();

  @override
  String toString() => 'CVFeedback("$feedbackText" at $timestamp)';
}
