// ============================================================
// firebase_options.dart — AUTO-GENERATED by FlutterFire CLI
//
// ⚠️  THIS IS A PLACEHOLDER FILE.
// You MUST replace this with your actual Firebase configuration.
//
// How to generate the real file:
//   1. Install FlutterFire CLI:
//        dart pub global activate flutterfire_cli
//   2. Run from the project root:
//        flutterfire configure
//   3. Select your Firebase project when prompted.
//   4. This file will be overwritten with your real config.
//
// Alternatively, copy the config values from:
//   Firebase Console → Project Settings → Your Apps → SDK setup
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // ──────────────────────────────────────────────────────────
  // ⚠️  REPLACE ALL VALUES BELOW with your Firebase project's
  //     actual configuration from the Firebase Console.
  // ──────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // ← replace
    appId: 'YOUR_ANDROID_APP_ID', // ← replace
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // ← replace
    projectId: 'YOUR_PROJECT_ID', // ← replace
    storageBucket: 'YOUR_PROJECT_ID.appspot.com', // ← replace
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // ← replace
    appId: 'YOUR_IOS_APP_ID', // ← replace
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // ← replace
    projectId: 'YOUR_PROJECT_ID', // ← replace
    storageBucket: 'YOUR_PROJECT_ID.appspot.com', // ← replace
    iosBundleId: 'com.yourcompany.kindredCareers', // ← replace
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY', // ← replace
    appId: 'YOUR_WEB_APP_ID', // ← replace
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // ← replace
    projectId: 'YOUR_PROJECT_ID', // ← replace
    storageBucket: 'YOUR_PROJECT_ID.appspot.com', // ← replace
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com', // ← replace
  );
}
